name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          npm install
          npm install electron-builder

      - name: Build electron app
        run: npm run build

      - name: Package Electron app
        run: npx electron-builder --win

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: operatorbird
          path: dist/**/*
